/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spa;

/**
 *
 * @author PC03
 */
public class tipos extends javax.swing.JFrame {

    /**
     * Creates new form tipos
     */
    public tipos() {
        initComponents();
        cbocombo.addItem("Corte");
        cbocombo.addItem("Peinado");
        cbocombo.addItem("Tinte");
        cbocombo.addItem("Mechas");
        cbocombo.addItem("Moldeado");
        cbocombo.addItem("Tratamiento");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbocombo = new javax.swing.JComboBox<>();
        cbntip = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtresultado = new javax.swing.JTextField();
        estilista1 = new javax.swing.JButton();
        barbero = new javax.swing.JButton();
        estilista2 = new javax.swing.JButton();
        insumo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtcosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("PELUQUERIA");

        cbocombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbocombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbocomboActionPerformed(evt);
            }
        });

        cbntip.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        cbntip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbntipActionPerformed(evt);
            }
        });

        jLabel2.setText("Seleccione");

        jLabel3.setText("Tipo");

        jLabel4.setText("PROFESIONAL");

        txtresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultadoActionPerformed(evt);
            }
        });

        estilista1.setText("Estilista1");
        estilista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estilista1ActionPerformed(evt);
            }
        });

        barbero.setText("Barbero");
        barbero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barberoActionPerformed(evt);
            }
        });

        estilista2.setText("Estilista2");
        estilista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estilista2ActionPerformed(evt);
            }
        });

        insumo.setText("Insumos");
        insumo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insumoActionPerformed(evt);
            }
        });

        jLabel5.setText("MONTO TOTAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbocombo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbntip, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addGap(186, 186, 186)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(170, 170, 170)
                                .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(estilista1)
                        .addGap(38, 38, 38)
                        .addComponent(barbero)
                        .addGap(91, 91, 91)
                        .addComponent(estilista2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(insumo)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(33, 33, 33)
                        .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbocombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbntip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barbero)
                    .addComponent(estilista2)
                    .addComponent(insumo)
                    .addComponent(estilista1))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtresultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbocomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbocomboActionPerformed
        String combo = (String) cbocombo.getSelectedItem();
        cbntip.removeAllItems();
        if (combo.equals("Corte")) {
            cbntip.addItem("Selecione");

            cbntip.addItem("corte de pelo mujer");
            cbntip.addItem("corte de pelo hombre");
            cbntip.addItem("corte de pelo infantil");
        }
        if (combo.equals("Peinado")) {
            cbntip.addItem("Selecione");
            cbntip.addItem("peinado");
            cbntip.addItem("peinado con rulos");
            cbntip.addItem("recogidos");
        }
        if (combo.equals("Tinte")) {
            cbntip.addItem("Selecione");
            cbntip.addItem("tinte o baño de color");
            cbntip.addItem("retoque color zona");
            cbntip.addItem("matizados");
        }
        if (combo.equals("Mechas")) {
            cbntip.addItem("Selecione");
            cbntip.addItem("mechas");
            cbntip.addItem("decoloracion");

        }
        if (combo.equals("Moldeado")) {
            cbntip.addItem("Selecione");
            cbntip.addItem("moldeado");
            cbntip.addItem("desrizado");
        }
        if (combo.equals("Tratamiento")) {
            cbntip.addItem("Selecione");
            cbntip.addItem("ritual express");
            cbntip.addItem("ritual intensive");
        }

    }//GEN-LAST:event_cbocomboActionPerformed

    private void cbntipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbntipActionPerformed
        String combos = (String) cbntip.getSelectedItem();

        if (combos == "corte") {
            txtcosto.setText("30");

        } else if (combos == "corte de pelo mujer") {
            txtcosto.setText("30");
            estilista1.setEnabled(false);
            estilista2.setEnabled(true);
            barbero.setEnabled(true);
            insumo.setEnabled(false);
        } else if (combos == "corte de pelo hombre") {
            txtcosto.setText("20");
            estilista1.setEnabled(false);
            estilista2.setEnabled(true);
            barbero.setEnabled(true);
            insumo.setEnabled(false);
        } else if (combos == "corte de pelo infantil") {
            txtcosto.setText("15");
            estilista1.setEnabled(false);
            estilista2.setEnabled(true);
            barbero.setEnabled(true);
            insumo.setEnabled(false);
        }
        if (combos == "peinado") {
            txtcosto.setText("14");
        } else if (combos == "peinado") {
            txtcosto.setText("14");
            estilista1.setEnabled(false);
            estilista2.setEnabled(true);
            barbero.setEnabled(true);
            insumo.setEnabled(false);
        } else if (combos == "peinado con rulos") {
            txtcosto.setText("18");
            estilista2.setEnabled(false);
            barbero.setEnabled(false);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        } else if (combos == "recogidos") {
            txtcosto.setText("18");
        }
        if (combos == "tinte") {
            txtcosto.setText("15");
        } else if (combos == "tinte o baño de color") {
            txtcosto.setText("15");
            estilista2.setEnabled(false);
            barbero.setEnabled(false);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        } else if (combos == "retoque color zona") {
            txtcosto.setText("15");
            estilista2.setEnabled(false);
            barbero.setEnabled(false);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        } else if (combos == "corte de pelo infantil") {
            txtcosto.setText("20");
            estilista2.setEnabled(false);
            barbero.setEnabled(true);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        }
        if (combos == "mechas") {
            txtcosto.setText("10");
        } else if (combos == "mechas") {
            txtcosto.setText("10");
            estilista2.setEnabled(true);
            barbero.setEnabled(false);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        } else if (combos == "decoloracion") {
            txtcosto.setText("16");
            estilista2.setEnabled(true);
            barbero.setEnabled(false);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        }
        if (combos == "moldeado") {
            txtcosto.setText("17");

        } else if (combos == "moldeado") {
            txtcosto.setText("17");
            estilista2.setEnabled(false);
            barbero.setEnabled(true);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        } else if (combos == "desrizado") {
            txtcosto.setText("15");
            estilista2.setEnabled(true);
            barbero.setEnabled(true);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        }
        if (combos == "tratamiento") {
            txtcosto.setText("");
        } else if (combos == "ritual express") {
            txtcosto.setText("25");
            estilista2.setEnabled(false);
            barbero.setEnabled(true);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        } else if (combos == "ritual intensive") {
            txtcosto.setText("18");
            estilista2.setEnabled(true);
            barbero.setEnabled(true);
            estilista1.setEnabled(true);
            insumo.setEnabled(true);
        }

    }//GEN-LAST:event_cbntipActionPerformed

    private void txtresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultadoActionPerformed

    }//GEN-LAST:event_txtresultadoActionPerformed

    private void estilista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estilista1ActionPerformed
        double total = 0;
        double precio = 0;
        precio = Double.parseDouble(txtcosto.getText());
        total = precio + ((precio * 12) / 100);
        txtresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_estilista1ActionPerformed

    private void barberoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barberoActionPerformed
        double total = 0;
        double precio = 0;
        precio = Double.parseDouble(txtcosto.getText());
        total = precio + ((precio * 8) / 100);
        txtresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_barberoActionPerformed

    private void estilista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estilista2ActionPerformed
        double total = 0;
        double precio = 0;
        precio = Double.parseDouble(txtcosto.getText());
        total = precio + ((precio * 7) / 100);
        txtresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_estilista2ActionPerformed

    private void insumoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insumoActionPerformed
        double total = 0;
        double precio = 0;
        precio = Double.parseDouble(txtcosto.getText());
        total = precio + ((precio * 15) / 100);
        txtresultado.setText(String.valueOf(total));
    }//GEN-LAST:event_insumoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barbero;
    private javax.swing.JComboBox<String> cbntip;
    private javax.swing.JComboBox<String> cbocombo;
    private javax.swing.JButton estilista1;
    private javax.swing.JButton estilista2;
    private javax.swing.JButton insumo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcosto;
    private javax.swing.JTextField txtresultado;
    // End of variables declaration//GEN-END:variables
}
