/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresarial;

/**
 *
 * @author Julio
 */
public class Sueldos extends javax.swing.JFrame {

    /**
     * Creates new form Sueldos
     */
    public Sueldos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbafp = new javax.swing.JLabel();
        lbboni = new javax.swing.JLabel();
        lbsueldoneto = new javax.swing.JLabel();
        btncalcular = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtsueldo = new javax.swing.JTextField();
        lbcomis1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel1.setText("SOYUS S.A");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 15, 196, 34));

        jLabel2.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel2.setText("SUELDO NETO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel3.setText("DESCUENTOS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 147, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel4.setText("BONIFICACIÓN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 147, -1, -1));

        jLabel5.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel5.setText("AFP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 60, 22));

        jLabel6.setFont(new java.awt.Font("Eras Demi ITC", 1, 14)); // NOI18N
        jLabel6.setText("COMISION AFP");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, 126, 29));
        getContentPane().add(lbafp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 26));
        getContentPane().add(lbboni, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 124, 21));
        getContentPane().add(lbsueldoneto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 150, 27));

        btncalcular.setText("CALCULAR");
        btncalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btncalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 100, 50));

        jLabel8.setFont(new java.awt.Font("Dubai", 1, 24)); // NOI18N
        jLabel8.setText("SUELDO BRUTO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 87, -1, -1));
        getContentPane().add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 150, 30));
        getContentPane().add(lbcomis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 126, 27));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 400, 370));

        jLabel11.setBackground(new java.awt.Color(255, 204, 51));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularActionPerformed
        Double a = Double.parseDouble(txtsueldo.getText());
        Double b = a*12/100;
        Double c = b*1/100;
        Double d = ((a-(b+c))*15)/100;
        Double e = (a-(b+c))+d;
       lbafp.setText(String.valueOf(b));
       lbcomis1.setText(String.valueOf(c));
       lbcomis1.setText(String.valueOf(c));
       lbboni.setText(String.valueOf(d));
       lbsueldoneto.setText(String.valueOf(e));
       
        
        
    }//GEN-LAST:event_btncalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sueldos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sueldos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbafp;
    private javax.swing.JLabel lbboni;
    private javax.swing.JLabel lbcomis1;
    private javax.swing.JLabel lbsueldoneto;
    private javax.swing.JTextField txtsueldo;
    // End of variables declaration//GEN-END:variables
}
